name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  check_workspace:
    name: Check the value of workspace
    runs-on: ubuntu-latest
    steps:        
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish --configuration Release -o './dist'
      
    - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1

    # - name: AWS Deploy S3    
    #   uses: oneyedev/aws-deploy-s3@v2
    #   with:       
    #     region: us-east-1  # default is us-east-1       
    #     bucket: code-deploy-bucket-ykim      
    #     source: ./dist # default is ./dist       
    #     target: GitHubActions # default is 