name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish --configuration Release -o './dist'
      
     
    - name: AWS Deploy S3
      # You may pin to the exact commit or the version.
      # uses: oneyedev/aws-deploy-s3@16e61e78e12904502d31e6c4adbe1f7d58eddaa7
      uses: oneyedev/aws-deploy-s3@v2
      with:
        # AWS Region of S3 Bucket
        region: us-east-1  # default is us-east-1
        # Name of S3 Bucket
        bucket: code-deploy-bucket-ykim
        # A Local Source Directory to Upload
        source: ./dist # default is ./dist
        # A Remote Target Directory to Upload
        target: GitHubActions # default is 