name: .NET-CICD-Pipeline
env: 
  DEPLOY_PACKAGE_NAME               : "dotnet_app_${{ GITHUB.RUN_ID }}_${{ GITHUB.RUN_NUMBER }}.zip"
  EB_PACKAGE_S3_BUCKET_NAME         : "code-deploy-bucket-ykim"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:
    runs-on: self-hosted
    steps:   
    - uses: actions/checkout@v2
    - name: print env path
      run: |
        echo "Work Space Directory is:"${{ github.workspace }}
        echo "Work Flow is:"${{ GITHUB.WORKFLOW }}
        echo "Build ID is:"${{ GITHUB.RUN_ID }}
        echo "Build Number is:"${{ GITHUB.RUN_NUMBER }}
        echo "Build.SourcesDirectory is:"$(Build.SourcesDirectory)
    - name: List current folder
      run: ls -la
    - name: Test AWS CLI installation
      run: aws --version
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
   
    - name: Restore dependencies
      run: dotnet restore
   
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore  
        zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./bin/Release/netcoreapp3.1
   
     
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Copy Deployment package to S3 bucket
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME}}/build    
   
